app/forms.py
from flask_wtf import FlaskForm 
from wtforms.fields import StringField, PasswordField, SubmitField, IntegerField
from wtforms.validators import DataRequired, Length, EqualTo, Email

class RegistrationForm(FlaskForm):
    username = StringField('Username', [DataRequired('Username cannot be empty'), Length(min=6, message = "Username should be at least 6 characters long") ])
    email = StringField('Email', [DataRequired("Email cannot be empty"), Email(message ="Invalid email address")])
    password = PasswordField('Password', [DataRequired('Password cannot be empty'), Length(min=8, message = "Password must be at least 8 characters long") ])
    confirm_password = PasswordField('Confirm Password', [DataRequired('This filed cannot be empty'), EqualTo('password', message="Passwords must match each other") ])
    register = SubmitField('Register')

class LoginForm(FlaskForm):
    username = StringField('Username', [DataRequired('Username cannot be empty') ])
    password = PasswordField('Password', [DataRequired('Password cannot be empty')])
    login = SubmitField('Login')

class InputForm(FlaskForm):
    Pclass = IntegerField(label ='Pclass', validators=[DataRequired('This feature cannot be empty')])
    sex = StringField(label ='Sex', validators=[DataRequired('This feature cannot be empty')])
    age = IntegerField(label ='Age', validators=[DataRequired('This feature cannot be empty') ])
    embarked = StringField(label ='Embarked', validators=[DataRequired('This feature cannot be empty')])
    predict = SubmitField('Predict')

app/__init__.py
from flask import Flask
from . import routes
from .database import User, db , Prediction, bcrypt

def create_app():
    app = Flask(__name__)
    app.config.from_object("config.Config")

    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///site.db"
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    db.init_app(app)
    bcrypt.init_app(app)

    app.register_blueprint(routes.bp)

    return app

app/routes.py
from flask import (
    render_template,
    redirect,
    url_for,
    flash,
    Blueprint,
    session,
    request,
)
import numpy as np 
from flask_bcrypt import Bcrypt
from .database import User, db, Prediction, bcrypt
from .forms import RegistrationForm, LoginForm, InputForm
from  .model.model import prediction_model

bp = Blueprint("main", __name__)
# bcrypt = Bcrypt()


@bp.route("/")
def home():
    return render_template("home.html")


@bp.route("/register", methods=["POST", "GET"])
def register():
    form = RegistrationForm()
    if request.method == 'POST' and form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        email = form.email.data

        existing_user = User.query.filter_by(username=username).first()
        if existing_user:
            flash("You already have an account. Please log in.", "warning")
            return redirect(url_for("main.login"))
        
        hashed_password = bcrypt.generate_password_hash(password).decode('utf8')
        new_user = User(username=username, password=hashed_password, email=email)
        db.session.add(new_user)
        db.session.commit()
        flash('Register Successfull')
        return redirect(url_for('main.login'))
    return render_template("register.html", form = form)

@bp.route("/login", methods=["POST", "GET"])
def login():
    form = LoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user_check = User.query.filter_by(username=username).first()
        if user_check is None:
            flash("This username is not registered. Please Register.", "warning")
            return redirect(url_for("main.login"))
        if user_check and bcrypt.check_password_hash(user_check.password, password):
            session['username'] = username
            flash("Login successful!", "success")
            return redirect(url_for('main.input_data'))
        else:
            flash("Login failed. Please check your username and password.", "danger")
            return redirect(url_for("main.login"))
    return render_template("login.html", form=form)

def login_required(f):
    def wrap(*args, **kwargs):
        if "username" not in session:
            flash("You need to login first!", "danger")
            return redirect(url_for("main.login"))
        return f(*args, **kwargs)

    wrap.__name__ = f.__name__
    return wrap


@bp.route("/input", methods=["GET", "POST"])
@login_required
def input_data():
    form=InputForm()

    if request.method == 'POST':
        sex = request.form.get("sex")
        age = request.form.get("age")
        pclass = request.form.get("pclass")
        embarked = request.form.get("embarked")

        if not sex or not age or not pclass or not embarked:
            flash("Missing data! Please fill out all fields.", "warning")
            return render_template("error.html",error = 400), 400  # Return custom error page with 400 status code
        
        features = [
            float(request.form['pclass']),
            request.form['sex'],
            float(request.form['age']),
            request.form['embarked']
        ]

        predicted_class = prediction_model(features)  ##machine learning model
        predict_result = 'Survived' if predicted_class == 1 else 'Not Survived'

        user_check = User.query.filter_by(username =session['username']).first()
        new_input = Prediction(
            user_id= user_check.id,
            Pclass = pclass,
            sex= sex,
            age= age,
            embarked = embarked,
            prediction_result = predict_result
        )
        db.session.add(new_input)
        db.session.commit()
        return render_template("result.html" , predicted_class = predicted_class)
       
    return render_template("input.html", form = form)

@bp.route("/history", methods=["GET"])
@login_required
def history():
    current_user = User.query.filter_by(username=session["username"]).first()
    predictions = Prediction.query.filter_by(user_id=current_user.id).all()
    # print(predictions[1].sex)
    return render_template("history.html", predictions=predictions)

@bp.route("/profile", methods=["GET"])
@login_required
def profile():
    current_user = User.query.filter_by(username=session["username"]).first()
    # predictions = Prediction.query.filter_by(user_id=current_user.id).all()
    # print(current_user.email)
    return render_template("profile.html", user_info=current_user)
    

@bp.route("/error", methods=["GET"])
def error():

    return render_template("error.html",error=500)


@bp.app_errorhandler(401)
def unauthorized_error(e):
    flash("You need to be logged in to access this page.", "warning")
    # return redirect(url_for("main.login"))
    return render_template("error.html",error=401), 401


@bp.app_errorhandler(404)
def page_not_found(e):
    return render_template("error.html",error=404), 404

@bp.app_errorhandler(500)
def internal_server_error(e):
    # Log the error details (optional, for debugging)
    # app.logger.error(f"Server Error: {e}")
    return render_template("error.html",error=500), 500



@bp.route("/logout")
def logout():
    session.pop("username",None)
    session.clear()
    flash("You are logged out", "success")

    return redirect(url_for("main.home"))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta
			content="width=device-width, initial-scale=1.0"
			name="viewport" />
		<title>{% block title %} {% endblock %}</title>
		<meta
			name="description"
			content="" />
		<meta
			name="keywords"
			content="" />
		<link
			href="{{url_for('static',filename='img/apple-touch-icon.png')}}"
			rel="apple-touch-icon" />
		<link
			href="{{url_for('static',filename='img/favicon.png')}}"
			rel="apple-touch-icon" />

		<!-- Fonts -->
		<link
			href="https://fonts.googleapis.com"
			rel="preconnect" />
		<link
			href="https://fonts.gstatic.com"
			rel="preconnect"
			crossorigin />
			<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
		<link
			href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
			rel="stylesheet" />

		<!-- Vendor CSS Files -->
		<link
			href="{{url_for('static',filename='vendor/bootstrap/css/bootstrap.min.css')}}"
			rel="stylesheet" />

		<link
			href="{{url_for('static',filename='vendor/bootstrap-icons/bootstrap-icons.css')}}"
			rel="stylesheet" />

		<link
			href="{{url_for('static',filename='vendor/aos/aos.css')}}"
			rel="stylesheet" />

		<link
			href="{{url_for('static', filename='vendor/glightbox/css/glightbox.min.css')}}"
			rel="stylesheet" />

		<link
			href="{{url_for('static', filename='vendor/swiper/swiper-bundle.min.css')}}"
			rel="stylesheet" />

		<!-- Main CSS File -->

		<link
			href="{{ url_for('static', filename='css/main.css') }}"
			rel="stylesheet" />
	</head>

	<body class="index-page">
		<header
			id="header"
			class="header d-flex align-items-center fixed-top">
			<div
				class="container-fluid container-xl position-relative d-flex align-items-center">
				<a
					href="#"
					class="logo d-flex align-items-center me-auto">
					<img src="{{url_for('static', filename='img/logo.png')}}">
					<h1 class="sitename">SurvivalReveal</h1>
				</a>

				<nav
					id="navmenu"
					class="navmenu">
					<ul>
						<li>
							<a href="{{ url_for('main.home') }}" 
							   class="{{ 'active' if request.endpoint == 'main.home' else '' }}">
								Home
							</a>
						</li>
						<li>
							<a href="{{ url_for('main.home') }}#about" 
							   class="{{ 'active' if request.endpoint == 'main.about' else '' }}">
								About
							</a>
						</li>
						<li>
							<a href="{{ url_for('main.home') }}#features" 
							   class="{{ 'active' if request.endpoint == 'main.features' else '' }}">
								History
							</a>
						</li>
						<li>
							<a href="{{ url_for('main.home') }}#contact" 
							   class="{{ 'active' if request.endpoint == 'main.contact' else '' }}">
								Contact
							</a>
						</li>
						<li>
							<a href="{{ url_for('main.input_data') }}" 
							   class="{{ 'active' if request.endpoint == 'main.input_data' else '' }}">
								Input Form
							</a>
						</li>
					</ul>
					<i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
				</nav>

				<!-- {% if session %}
							<pre>{{ session }}</pre>
							{% endif %} {% if 'username' in session %} -->
							<!-- User is logged in, show the logout button -->
					<a
						class="btn-getstarted"
						href="{{ url_for('main.logout') }}"
						>Logout</a
					>
					<a
						class="btn-getstarted"
						href="{{ url_for('main.profile') }}"
						>Profile</a
					>
				{% else %}
					<!-- User is not logged in, show the login and register buttons -->
					<a
						class="btn-getstarted"
						href="{{url_for('main.login')}}"
						>Log In</a
					>
					<a
						class="btn-getstarted"
						href="{{url_for('main.register')}}"
						>Register</a
					>
				{% endif %}
			</div>
		</header>
		<main>{% block content %}{% endblock %}</main>
		<footer
			id="footer"
			class="footer position-relative light-background">

			<div class="container copyright text-center mt-4">
				<p>
					© <span>Copyright</span>
					<strong class="px-1 sitename">SurvivalReveal</strong
					><span>All Rights Reserved</span>
				</p>
				<div class="credits">
					<!-- All the links in the footer should remain intact. -->
					<!-- You can delete the links only if you've purchased the pro version. -->
					<!-- Licensing information: https://bootstrapmade.com/license/ -->
					<!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
					Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
				</div>
			</div>
		</footer>

		<!-- Scroll Top -->
		<a
			href="#"
			id="scroll-top"
			class="scroll-top d-flex align-items-center justify-content-center"
			><i class="bi bi-arrow-up-short"></i
		></a>

		<!-- Preloader -->
		<div id="preloader"></div>

		<!-- Vendor JS Files -->
		<script src="{{url_for('static',filename='vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
		<script src="{{url_for('static',filename='vendor/php-email-form/validate.js')}}"></script>

		<script src="{{url_for('static',filename='vendor/aos/aos.js')}}"></script>
		<script src="{{url_for('static',filename='vendor/glightbox/js/glightbox.min.js')}}"></script>

		<script src="{{url_for('static',filename='vendor/swiper/swiper-bundle.min.js')}}"></script>

		<!-- Main JS File -->
		<script src="{{ url_for('static', filename='js/main.js')}}"></script>
	</body>
</html>

app/templates/error.html
{%extends "base.html" %} {% block title %} Input {% endblock %} {% block content
	%}
	<section>
		<div
			class="container"
			data-aos="fade-up">
			{% if error == 400 %}
			<div class="row d-flex justify-content-center align-items-center mt-5 p-4">
				<div class="col-lg-5">
					<div>
						<img
							class="error"
							src="{{ url_for('static', filename='img/errors/400.jpg') }}"
							alt="400 Error Image" />
					</div>
				</div>
				<div class="col-lg-5">
					<h1>Bad Request (400)</h1>
					<p>
						It looks like some required data is missing or invalid. Please go back
						and try again.
					</p>
					<a href="{{ url_for('main.input_data') }}">Return to Input Page</a>
				</div>
			</div>
		</div>
		{% endif %}
		{% if error == 401 %}
			<div class="row d-flex justify-content-center align-items-center mt-5 p-4">
				<div class="col-lg-5">
					<div>
						<img
							class="error"
							src="{{ url_for('static', filename='img/errors/401.jpg') }}"
							alt="401 Error Image" />
					</div>
				</div>
				<div class="col-lg-5">
					<h1>Unauthorized Error (401)</h1>
					<p>
						You need to be logged in to access this page
					</p>
					<a href="{{ url_for('main.login') }}">Login</a>
				</div>
			</div>
		</div>
		{% endif %}
		{% if error == 404 %}
			<div class="row d-flex justify-content-center align-items-center mt-5 p-4">
				<div class="col-lg-5">
					<div>
						<img
							class="error"
							src="{{ url_for('static', filename='img/errors/404-2.png') }}"
							alt="404 Error Image" />
					</div>
				</div>
				<div class="col-lg-5">
					<h1>404 - Page Not Found</h1>
					<p>Sorry, the page you're looking for doesn't exist.</p>
					<a href="{{ url_for('main.home') }}">Return to Home</a>
				</div>
			</div>
		</div>
		{% endif %}
		{% if error == 500 %}
			<div class="row d-flex justify-content-center align-items-center mt-5 p-4">
				<div class="col-lg-5">
					<div>
						<img
							class="error"
							src="{{ url_for('static', filename='img/errors/500-2.png') }}"
							alt="500 Error Image" />
					</div>
				</div>
				<div class="col-lg-5">
					<h1>500 - Internal Server Error</h1>
        			<p>Oops! Something went wrong on our end. Please try again later.</p>
					<a href="{{ url_for('main.home') }}">Return to Home</a>
				</div>
			</div>
		</div>
		{% endif %}
	</section>
	{%endblock%}
	

app/templates/history.html
{% extends "base.html" %}
{% block title %} History {% endblock %}
{% block content %}
<section id="login" class="hero result section">
    <!-- Section Title -->
    <div class="login-bg">
        <img src="{{ url_for('static', filename='img/input.jpg') }}" alt="" />
    </div>
    <div class="container" data-aos="fade-up">
        <div class="row d-flex justify-content-center align-items-start">
            <div class="col-lg-6">
                <h4 class="section-title text-center">Prediction History</h4>
                <p class="text-center">Your prediction history is:</p>
                
                <!-- Table for Prediction Results -->
                <table class="table table-striped text-center">
                    <thead>
                        <tr>
                            <th>Prediction #</th>
                            <th>Sex</th>
                            <th>Age</th>
                            <th>Ticket class</th>
                            <th>Port of Embarkation</th>
                            <th>Prediction</th>							
                        </tr>
                    </thead>
                    <tbody>
                        {% for prediction in predictions %}
                        <tr>
                            <td>{{ loop.index }}</td>
                            <td>{{ prediction.sex }}</td>
                            <td>{{ prediction.age }}</td>
                            <td>{{ prediction.Pclass }}</td>
                            <td>{{ prediction.embarked }}</td>
                            <td>{{ prediction.prediction_result }}</td>


                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                
                <!-- Explanation -->
                <p class="text-center mt-3">
                    Here is a summary of your recent predictions based on the input data provided.
                </p>
                
                <!-- Predict More Button -->
                <div class="text-center">
                    <a href="{{ url_for('main.input_data') }}" class="btn-get-started">Predict more</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/input.html
{%extends "base.html" %} {% block title %} Input {% endblock %} {% block
	content %}
<section
	id="login"
	class="hero login section">
	<!-- Section Title -->
	<div class="login-bg">
		<img
			src="{{url_for('static',filename='img/input.jpg')}}"
			alt="" />
	</div>
	<div
		class="container"
		data-aos="fade-up">
		<div class="row d-flex justify-content-center align-items-start">
			<h2 class="section-title">Enter your Data</h2>

			<div class="col-lg-3">
				<form method="POST">
					<div class="mb-3">
						<div class="mb-3">
							<label for="pclass" class="form-label">Sex</label>
							<select class="form-control" id="pclass" name="sex">
								<option class="text-muted" disabled selected>choose sex</option> <!-- Placeholder -->
								<option value='male'>Male</option>
								<option value='female'>Female</option>
							</select>
						</div>
					</div>
					<div class="mb-3">
						<label
							for="feature2"
							class="form-label"
							>Age</label
						>
						<input
							type="text"
							class="form-control"
							id="age"
							name="age"
							placeholder="Enter age" />
                    </div>
                </div>
                <div class="col-lg-3">

                    <div class="mb-3">
						<label for="pclass" class="form-label">Ticket class</label>
						<select class="form-control" id="pclass" name="pclass">
							<option class="text-muted" disabled selected>Ticket class</option> <!-- Placeholder -->
							<option value=1>First Class</option>
							<option value=2>Second Class</option>
							<option value=3>Third Class</option>
						</select>
					</div>
					
					
					<div class="mb-3">
						<label for="embarked" class="form-label">Port of Embarkation</label>
						<select class="form-control" id="embarked" name="embarked">
							<option value="" class="text-muted" disabled selected>Port of Embarkation</option> <!-- Placeholder -->
							<option value="C">Cherbourg</option>
							<option value="Q">Queenstown</option>
							<option value="S">Southampton</option>
						</select>
					</div>
					
                </div>
					<div class="d-flex justify-content-center p-3">
						<button
							type="submit"
							class="submit-btn">
							Predict
						</button>
					</div>
					<div class="text-center">
						<p>
							Do you want to see previous predictions?
							<a href="{{url_for('main.history')}}">See your history</a>
						</p>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>
<!-- /Starter Section Section -->
{%endblock%}

app/templates/login.html
{%extends "base.html" %} {% block title %} Sign In {% endblock %} {% block
	content %}
<section
	id="login"
	class="hero login section">
	<!-- Section Title -->
	<div class="login-bg">
		<img
			src="{{url_for('static',filename='img/login_bg.jpg')}}"
			alt="" />
	</div>
	<div
		class="container "
		data-aos="fade-up">
		<div class="row d-flex flex-column align-items-end p-3">
			<div class="col-lg-6 section-title text-center">
				<h2>Sign In</h2>
			</div>
			{% with  messages = get_flashed_messages(with_categories=true) %}
			{% if messages %}
			<div>
				{% for category, message in messages %}
					<div class="alert alert-{{category}} alert-dismissiable fade show" role="alert">
						{{message}}
					</div>
				{% endfor %}
			</div>
			{% endif %}
			{% endwith %}

			<div class="col-lg-6">
				<form action="{{url_for('main.login')}}" method="post" novalidate>
					{{form.csrf_token}}
					<div class="form-group">
						{{form.username.label}}
						{{form.username(class='form-control')}}
						{% for error in form.username.errors%}
							<span style="color: red;">[{{ error }}]</span><br>
						 {%endfor%}
					</div>
					<div class="form-group">
						{{form.password.label}}
						{{form.password(class='form-control')}}
						{% for error in form.password.errors%}
							<span style="color: red;">[{{ error }}]</span><br>
						 {%endfor%}
					</div>
			
					<div class="d-flex justify-content-center p-3">
                        {{form.login(class="submit-btn")}}
                    </div>
                    <div class="text-center">
                        <p>Don't have an account? <a href="{{url_for('main.register')}}">Sign up here</a></p>
                    </div>
				</form>
			</div>
		</div>
	</div>
	
</section>
<!-- /Starter Section Section -->
{%endblock%}

app/templates/profile.html
{%extends "base.html" %} {% block title %} Profile {% endblock %} 
{% block content %}
<section id="login" class="hero result section">
    <!-- Section Title -->
    <div class="login-bg">
        <img src="{{ url_for('static', filename='img/input.jpg') }}" alt="" />
    </div>
    <div class="container" data-aos="fade-up">
        <div class="row d-flex justify-content-center align-items-start">
            <div class="col-lg-6">
                <h4 class="section-title text-center">Profile</h4>
                
                <!-- Table for Prediction Results -->
                <table class="table table-striped text-center">
                    <thead>
                        <tr>
                            <th>Username</th>
                            <th>Email</th>							
                        </tr>
                    </thead>
                    <tbody>
                        
                        <tr>
                            <td>{{ user_info.username }}</td>
                            <td>{{ user_info.email }}</td>
                        </tr>
                    </tbody>
                </table>
                
                <!-- Explanation -->
                <p class="text-center mt-3">
                   see your history here
                </p>
                
                <!-- Predict More Button -->
                <div class="text-center">
                    <a href="{{ url_for('main.history') }}" class="btn-get-started">history</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/register.html
{%extends "base.html" %} {% block title %} Sign Up {% endblock %} {% block
	content %}
<section
	id="login"
	class="hero login section">
	<!-- Section Title -->
	<div class="login-bg">
		<img
			src="{{url_for('static',filename='img/login_bg.jpg')}}"
			alt="" />
	</div>
	<div
		class="container "
		data-aos="fade-up">
		<div class="row d-flex flex-column align-items-end p-3">
			{% with  messages = get_flashed_messages(with_categories=true) %}
			{% if messages %}
			<div>
				{% for category, message in messages %}
					<div class="alert alert-{{category}} alert-dismissiable fade show" role="alert">
						{{message}}
					</div>
				{% endfor %}
			</div>
			{% endif %}
			{% endwith %}
			<div class="col-lg-6 section-title text-center">
				<h2>Sign Up</h2>
			</div>

			<div class="col-lg-6">
				<form action="{{url_for('main.register')}}" method="post" novalidate>
					{{form.hidden_tag()}}

					<div class="form-group">
						{{form.username.label}}
						{{form.username(class='form-control')}}
						{% for error in form.username.errors%}
							<span style="color: red;">[{{ error }}]</span><br>
						 {%endfor%}
					</div>
					<div class="form-group">
						{{form.email.label}}
						{{form.email(class='form-control')}}
						{% for error in form.email.errors%}
							<span style="color: red;">[{{ error }}]</span><br>
						 {%endfor%}
					</div>
			
					<div class="form-group">
						{{form.password.label}}
						{{form.password(class='form-control')}}
						{% for error in form.password.errors%}
							<span style="color: red;">[{{ error }}]</span><br>
						 {%endfor%}
					</div>
			
					<div class="form-group">
						{{form.confirm_password.label}}
						{{form.confirm_password(class='form-control')}}
						{% for error in form.confirm_password.errors%}
							<span style="color: red;">[{{ error }}]</span><br>
						 {%endfor%}
					</div>
			
					
					<div class="d-flex justify-content-center p-3">
                        {{form.register(class='submit-btn')}}
                    </div>
                    <div class="text-center">
                        <p>Already have an account? <a href="{{url_for('main.login')}}">Sign In here</a></p>
                    </div>
				</form>
			</div>
		</div>
	</div>
	
</section>
<!-- /Starter Section Section -->
{%endblock%}

app/templates/result.html
{%extends "base.html" %} {% block title %} Result {% endblock %} {% block
content %}
<section
	id="login"
	class="hero result section">
	<!-- Section Title -->
	<div class="login-bg">
		<img
			src="{{url_for('static',filename='img/input.jpg')}}"
			alt="" />
	</div>
	<div
		class="container"
		data-aos="fade-up">
		<div class="row d-flex justify-content-center align-items-start">
			<div class="col-lg-6">
				<h4 class="section-title text-center">Predicted result</h4>
				<p class="text-center">
					The predicted result is:
					<!-- put prediction result here with jinja -->
					<strong
						>{% if predicted_class == 0 %} Not Survived {% elif predicted_class
						== 1 %} Survived {% else %} Unknown {% endif %}</strong
					>
				</p>
				<!-- add explanation with jinja-->
				<p class="text-center">
					{% if predicated_class == 1%} According to our data and prediction,
					you would have survived the Titanic disaster. {% elif predicted_class
					== 0 %} According to our data and prediction, you wouldn't have
					survived the Titanic disaster. {% else %} We encountered an error
					while predicting your survival status. Please try again later. {%
					endif %}
				</p>
				<div class="text-center">
					<a
						href="{{url_for('main.input_data')}}"
						class="btn-get-started"
						>Predict Again</a
					>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- /Starter Section Section -->
{%endblock%}